[package]
name = "kvs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap =  "4.5.9"
tempfile = "3.10.1"
walkdir = "2.5.0"
serde = "1.0.204"
serde_json = "1.0.120"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"